config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'travels#index'
  resources :travels, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/travel.rb
class Travel < ApplicationRecord
  validates :title,           presence: true
  validates :description,     presence: true
  validates :place,           presence: true
  
  has_one_attached :image
  belongs_to :user
  
end

app/models/user.rb
class User < ApplicationRecord
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname,        presence: true, format: { with: /\A[ぁ-んァ-ヶ一\p{Han}]+\z/ }
  validates :age,             presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 10, less_than_or_equal_to: 120 }
 
       
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze
  validates :password, format: { with: VALID_PASSWORD_REGEX, message: "は半角英数を両方含む必要があります"}
         
  has_many :travels
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?


  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :age])
  end

end

app/controllers/travels_controller.rb
class TravelsController < ApplicationController
  before_action :authenticate_user!, only: [:new ]


  def index
  end

  def new
    @travel = Travel.new
  end

  def create
    @travel = Travel.new(travel_params)
    if @travel.save
      redirect_to '/'
    else 
      render :new, status: :unprocessable_entity
    end
  end

  private

  def travel_params
    params.require(:travel).permit(:title, :description, :place, :image).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/travels_helper.rb
module TravelsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TravelsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/travels/_fotter.html.erb
<div class='footer'>
  <div class='footer-contents'>
    <div class='furima-details'>
      <h2 class='footer-content-head'>旅ナビについて</h2>
      <ul>
        <li><%= link_to '運営情報', "#", class: "footer-link" %></li>
        <li><%= link_to 'プライバシーポリシー', "#", class: "footer-link" %></li>
        <li><%= link_to '旅ナビ利用規約', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>おすすめの旅行</h2>
      <ul>
        <li><%= link_to 'エリアから探す', "#", class: "footer-link" %></li>
        <li><%= link_to 'カテゴリーから探す', "#", class: "footer-link" %></li>
      </ul>
    </div>
  </div>
 
  <p>© 旅ナビ</p>
</div>

app/views/travels/_header.html.erb
<div class = "main-header">
  <div class="header-name">
    <%= link_to '旅ナビ', root_path, class: "top-page" %>
  </div>

  <div class = "prefecture">
    <a href = "#">エリアから探す</a>
  </div>

  <div class = "category">
    <a href = "#">カテゴリーから探す</a>
  </div>

  <% if user_signed_in? %>
  <div class="create-travel-navi">
    <%= link_to '旅行ナビを作成する', new_travel_path, class: "sign-up" %>
  </div>
  <% end %>
</div>

<div class = "rigth-header">

  <% if user_signed_in? %>
    <div class = "login_name">
      <%= current_user.nickname  %>
    </div>
    <div class = "logout">
      <%= link_to 'ログアウト', destroy_user_session_path, data: {turbo_method: :delete}, class: "logout" %>
    </div>
  <% else %>
    <div class = "login">
      <%= link_to 'ログイン', new_user_session_path, class: "sign-up" %>
    </div>
    <div class = "new-user">
      <%= link_to '新規登録', new_user_registration_path, class: "sign-up" %>
    </div>
  <% end %>

</div>

app/views/travels/index.html.erb
<div class="wrapper">

  <div class = "header">
    <%= render "header" %>
  </div>

  <div class ="image">
    <%= image_tag "travels-navi.png", class:"list-pict" %>
  </div>

  <div class = "main">
    <div class = "post">
      <h2 class = "title">
        ⚫️観光地
      </h2>

      <%= image_tag "uzushio.jpeg", class:"list-1" %>
      <%= image_tag "kazurabashi.jpeg", class:"list-1" %>
      <%= image_tag "otsuka.JPG", class:"list-1" %>
    </div>


    
  <iframe src="https://storage.googleapis.com/maps-solutions-q7q5z6ob6j/commutes/k4pd/commutes.html"
    width="100%" height="100%"
    style="border:0;"
    loading="lazy">
  </iframe>


  <div class = "fotter">
    <%= render "fotter" %>
  </div>
</div>

app/views/travels/new.html.erb
<div class = "header">
    <%= render "header" %>
</div>

<div class="taravel-content">
 
  <div class="items-sell-main">
    <h2 class="items-sell-title">観光地の情報を入力</h2>
    <%= form_with(model: @travel,local: true) do |f| %>

    <%# 商品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        観光地の写真
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /商品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        観光地名
      </div>
      <%= f.text_area :title, class:"travels-text", id:"title", placeholder:"公式名称で記載", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          観光地の説明
        </div>
        <%= f.text_area :description, class:"travels-text", id:"description", placeholder:"観光地の説明 例）1,2時間で愛染体験ができます" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>

    <div class="weight-bold-text">
        住所
      </div>
    <%= f.text_area :place, class:"travels-text", id:"place", placeholder:"公式から引用", maxlength:"100" %>
    <%# /商品名と商品説明 %>

    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "投稿する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

</div>

<div class = "fotter">
    <%= render "fotter" %>
</div>